Require Boost headers
Error :
 greenlib/build/include/gsgpsocket/transport/../core/attributes.h:27:54: fatal
 error: boost/config.hpp: No such file or directory
 #include <boost/config.hpp> // needed for SystemC 2.1

Signed-off-by: Guillaume Delbergue <guillaume.delbergue@greensocs.com>